[tool.poetry]
name = "itch-dl"
packages = [{ include = "itchdl" }]
version = "0.1.0"
description = "itch.io bulk game downloader"
homepage = "https://github.com/DragoonAethis/itch-dl"
repository = "https://github.com/DragoonAethis/itch-dl"
authors = ["Dragoon Aethis <dragoon@dragonic.eu>"]
readme = "README.md"
license = "MIT"

classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Topic :: System :: Archiving :: Backup",
    "Topic :: Games/Entertainment",
    "Topic :: Utilities",
    "Typing :: Typed"
]

[tool.poetry.urls]
"Wiki" = "https://github.com/DragoonAethis/itch-dl/wiki"
"Bug Tracker" = "https://github.com/DragoonAethis/itch-dl/issues"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.26.0"
python-slugify = "^5.0.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
